name: BadPiggy
main: BadPiggy\Main
version: 1.0.0 BETA
api: 2.0.0
author: MCPEPIG

permissions:
 badpiggy:
  default: op
  description: "Allows using all BadPiggy features" 
  children:
    badpiggy.command:
      default: op
      description: "Allow using all BadPiggy commands"
      children:
        badpiggy.command.fall:
          default: op
          description: "Allow using the fall subcommand"
        badpiggy.command.explode:
          default: op
          description: "Allow using the explode subcommand"  
        badpiggy.command.burn:
          default: op
          description: "Allow using the burn subcommand"     
        badpiggy.command.void:
          default: op
          description: "Allow using the void subcommand"  
        badpiggy.command.fexplode:
          default: op
          description: "Allow using the fexplode subcommand"  