name: BadPiggy
main: BadPiggy\Main
version: 1.0.1 BETA3
api: 2.0.0
author: MCPEPIG

permissions:
 badpiggy:
  default: op
  description: "Allows using all BadPiggy features" 
  children:
    badpiggy.command:
      default: op
      description: "Allow using all BadPiggy commands"
      children:
        badpiggy.command.fall:
          default: op
          description: "Allow using the fall subcommand"
        badpiggy.command.explode:
          default: op
          description: "Allow using the explode subcommand" 
        badpiggy.command.strike:
          default: op
          description: "Allow using the strike subcommand"   
        badpiggy.command.burn:
          default: op
          description: "Allow using the burn subcommand"  
        badpiggy.command.infall:
          default: op
          description: "Allow using the infall subcommand"  
        badpiggy.command.web:
          default: op
          description: "Allow using the web subcommand"     
        badpiggy.command.void:
          default: op
          description: "Allow using the void subcommand" 
        badpiggy.command.invoid:
          default: op
          description: "Allow using the invoid subcommand"  
        badpiggy.command.lavablock:
          default: op
          description: "Allow using the lavablock subcommand"  
        badpiggy.command.hole:
          default: op
          description: "Allow using the hole subcommand"  
        badpiggy.command.teleport:
          default: op
          description: "Allow using the teleport subcommand"  
        badpiggy.command.freeze:
          default: op
          description: "Allow using the freeze subcommand"  
        badpiggy.command.fexplode:
          default: op
          description: "Allow using the fexplode subcommand"  
        badpiggy.command.blind:
          default: op
          description: "Allow using the blind subcommand" 
        badpiggy.command.drunk:
          default: op
          description: "Allow using the drunk subcommand"  
        badpiggy.command.starve:
          default: op
          description: "Allow using the starve subcommand"  
        badpiggy.command.slow:
          default: op
          description: "Allow using the slow subcommand" 
        badpiggy.command.poison:
          default: op
          description: "Allow using the poison subcommand" 
        badpiggy.command.strip:
          default: op
          description: "Allow using the strip subcommand"  
        badpiggy.command.glass:
          default: op
          description: "Allow using the glass subcommand"  
        badpiggy.command.shoot:
          default: op
          description: "Allow using the shoot subcommand" 
        badpiggy.command.anvil:
          default: op
          description: "Allow using the anvil subcommand" 
        badpiggy.command.babble:
          default: op
          description: "Allow using the babble subcommand"  
        badpiggy.command.spin:
          default: op
          description: "Allow using the spin subcommand" 
        badpiggy.command.unaware:
          default: op
          description: "Allow using the unaware subcommand"  
        badpiggy.command.leveldown:
          default: op
          description: "Allow using the leveldown subcommand"
        badpiggy.command.surround:
          default: op
          description: "Allow using the surround subcommand"
        badpiggy.command.flamingarrow:
          default: op
          description: "Allow using the flamingarrow subcommand"
        badpiggy.command.night:
          default: op
          description: "Allow using the night subcommand"
        badpiggy.command.rewind:
          default: op
          description: "Allow using the rewind subcommand"
        badpiggy.command.slap:
          default: op
          description: "Allow using the slap subcommand"
        badpiggy.command.lag:
          default: op
          description: "Allow using the lag subcommand"
        badpiggy.command.exblock:
          default: op
          description: "Allow using the exblock subcommand"  
        badpiggy.command.mute:
          default: op
          description: "Allow using the mute subcommand"  
        badpiggy.command.spam:
          default: op
          description: "Allow using the spam subcommand" 
        badpiggy.command.cage:
          default: op
          description: "Allow using the cage subcommand" 
        badpiggy.command.fakeop:
          default: op
          description: "Allow using the fakeop subcommand" 
        badpiggy.command.popup:
          default: op
          description: "Allow using the popup subcommand" 
        badpiggy.command.potato:
          default: op
          description: "Allow using the potato subcommand" 
        badpiggy.command.popular:
          default: op
          description: "Allow using the popular subcommand"   
        badpiggy.command.display:
          default: op
          description: "Allow using the display subcommand"   
        badpiggy.command.pumpkin:
          default: op
          description: "Allow using the pumpkin subcommand"  
        badpiggy.command.armour:
          default: op
          description: "Allow using the armour subcommand"  
        badpiggy.command.tree:
          default: op
          description: "Allow using the tree subcommand"  
        badpiggy.command.maim:
          default: op
          description: "Allow using the maim subcommand"  
        badpiggy.command.brittle:
          default: op
          description: "Allow using the brittle subcommand"  
        badpiggy.command.tnttrick:
          default: op
          description: "Allow using the tnttrick subcommand"  
        badpiggy.command.tnt:
          default: op
          description: "Allow using the tnt subcommand"
        badpiggy.command.fire:
          default: op
          description: "Allow using the fire subcommand" 
        badpiggy.command.squid:
          default: op
          description: "Allow using the squid subcommand"  
        badpiggy.command.crash:
          default: op
          description: "Allow using the crash subcommand"  
        badpiggy.command.useless:
          default: op
          description: "Allow using the scream subcommand"  
        badpiggy.command.idtheft:
          default: op
          description: "Allow using the idtheft subcommand"  
        badpiggy.command.scream:
          default: op
          description: "Allow using the scream subcommand" 
        badpiggy.command.trip:
          default: op
          description: "Allow using the trip subcommand" 
        badpiggy.command.potate:
          default: op
          description: "Allow using the potate subcommand" 
        badpiggy.command.chat:
          default: op
          description: "Allow using the chat subcommand"  
        badpiggy.command.rename:
          default: op
          description: "Allow using the rename subcommand"         
        badpiggy.command.kick:
          default: op
          description: "Allow using the kick subcommand"        
        badpiggy.command.sudo:
          default: op
          description: "Allow using the sudo subcommand"   
        badpiggy.command.end:
          default: op
          description: "Allow using the end subcommand" 
        badpiggy.command.stop:
          default: op
          description: "Allow using the stop subcommand"   