#                                                                                     
#                                 ,-.----.                                            
#    ,---,.                       \    /  \                                           
#  ,'  .'  \                 ,---,|   :    \   ,--,                                   
#,---.' .' |               ,---.'||   |  .\ :,--.'|                                   
#|   |  |: |               |   | :.   :  |: ||  |,     ,----._,.  ,----._,.           
#:   :  :  /  ,--.--.      |   | ||   |   \ :`--'_    /   /  ' / /   /  ' /     .--,  
#:   |    ;  /       \   ,--.__| ||   : .   /,' ,'|  |   :     ||   :     |   /_ ./|  
#|   :     \.--.  .-. | /   ,'   |;   | |`-' '  | |  |   | .\  .|   | .\  ., ' , ' :  
#|   |   . | \__\/: . ..   '  /  ||   | ;    |  | :  .   ; ';  |.   ; ';  /___/ \: |  
#'   :  '; | ," .--.; |'   ; |:  |:   ' |    '  : |__'   .   . |'   .   . |.  \  ' |  
#|   |  | ; /  /  ,.  ||   | '/  ':   : :    |  | '.'|`---`-'| | `---`-'| | \  ;   :  
#|   :   / ;  :   .'   \   :    :||   | :    ;  :    ;.'__/\_: | .'__/\_: |  \  \  ;  
#|   | ,'  |  ,     .-./\   \  /  `---'.|    |  ,   / |   :    : |   :    :   :  \  \ 
#`----'     `--`---'     `----'     `---`     ---`-'   \   \  /   \   \  /     \  ' ; 
#                                                       `--`-'     `--`-'       `--` 

#Max radius for teleport punishment
teleport-radius: 500
surround-radius: 50
                                                       